### ISSUE TITLE
.dockerignore is being ignored

### ISSUE THREAD

**Issue by felixbr** [makeusabrew/decking#81]
Hi,

I've tried to have a subfolder for each container (web, db, etc.) and building works fine, but my .dockerignore file doesn't work no matter where I put it.

Imo it should be copied alongside the Dockerfile into the root directory or there needs to be some decking specific config to ignore folders and files.

This is especially important if you have a big folder/file in your root directory, as it will be sent to the host-vm docker deamon (I'm using vagrant for this), which can cause a error 500 or at least a really long waiting period.

**Comment by felixbr** [comment]
After some more tinkering, it seems this is an issue with docker or the vm-host and not with decking itself.

I still think it would be helpful if .dockerignore files would be copied alongside the Dockerfile.

**Comment by makeusabrew** [comment]
Thanks for this report @felixbr. I'm going to try and spend some time getting my head back into this project over the coming month or so. The docker ecosystem is a nightmare to keep up with - the last time I seriously used it (docker) there was no concept of a `.dockerignore` file!
